# Generated by Django 4.0.6 on 2022-07-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_good_article_remove_measure_m_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.measure'),
        ),
    ]
