# Generated by Django 4.0.6 on 2022-07-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_good_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.measure'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_stock', models.DecimalField(decimal_places=2, max_digits=5)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.good')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.store')),
            ],
        ),
    ]
