# Generated by Django 4.0.6 on 2022-07-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_good_measure_unit_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.good'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_id',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_store', to='blog.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_store', to='blog.store'),
        ),
    ]
